// the sturcture of this file is based on the default layout file generated by Next.js 
// when creating a new app with the command `npx create-next-app@latest --app`


import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "مساعد المبيعات الذكي",
  description: "حوّل المحادثات إلى عملاء وصفقات تلقائيًا.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className="h-full antialiased">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
